# Nombre
name: Deploy to Server

# evento
on: push

# jobs
jobs:
  first_job:
    # definimos el runner
    runs-on: ubuntu-latest
    # pasos
    steps:
      - name: Hola Mundo
        run: echo "Hola mundo"

  second_job:
    # condición para ejecutar el job
    if: false
    # needs indica que este job depende del primero (first_job)
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el segundo job"
