# Nombre
name: Deploy to Server

# evento
on: push

# jobs
jobs:
  first_job:
    # definimos el runner
    runs-on: ubuntu-latest

    #salidas 
    outputs:
      salida: ${{ steps.step_1.outputs.Mi_variable }}
    #Variables de entorno
    env:
      NAME: CodigoFacilito

    # pasos
    steps:
      - name: Working dir
        id: step_1
        run: echo "Mi_variable=Hola mundo" >> $GITHUB_OUTPUT

      - name: Optener mensaje
        run: echo "${{ steps.step_1.outputs.Mi_variable }}"

  second_job:
      # condición para ejecutar el job
    if: ${{ github.ref == 'refs/heads/main' }}
      # needs indica que este job depende del primero (first_job)
    needs: first_job
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}

    steps:
      - name: Hola mundo
        run: echo "$SALIDA"
