# Nombre
name: Deploy to Server

# evento
on: push

# jobs
jobs:
  first_job:
    # definimos el runner
    runs-on: ubuntu-latest
    # pasos
    steps:
      - name: Hola Mundo
        run: echo "Hola mundo"

  secod_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el segundo job"