# Nombre
name: Deploy to Server

# evento
on: push

# jobs
jobs:
  first_job:
    # definimos el runner
    runs-on: ubuntu-latest
    #Variables de entorno
    env:
      NAME: CodigoFacilito

    # pasos
    steps:
      - name: Working dir
        id: step_id
        run: echo "Mi_variable=Hola mundo" >> $GITHUB_OUTPUT

      - name: Optener mensaje
        run: echo "${{ steps.step_id.outputs.Mi_variable }}"

  second_job:
      # condición para ejecutar el job
    if: ${{ github.ref == 'refs/heads/main' }}
      # needs indica que este job depende del primero (first_job)
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el segundo job"
