# Nombre
name: Deploy to Server

# evento
on: push

# jobs
jobs:
  first_job:
    # definimos el runner
    runs-on: ubuntu-latest

    #salidas 
    outputs:
      salida: ${{ steps.step_1.outputs.Mi_variable }}
    #Variables de entorno
    env:
      NAME: CodigoFacilito

    # pasos
    steps:
      - name: generar archivo
        run |
          echo "Archivo prueba, hola" >> test.log

      - name: subir artefacto
        uses: action/upload-artifact@v4
        # parametros
        with:
          name: archivo-test
          path: test.log