# Nombre
name: Deploy to Server

# evento
on: push

# jobs
jobs:
  first_job:
    # definimos el runner
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        message: ['Hola', 'CodigoFacilito', "Bootcamp GitHub Actions"]
    #salidas 
    outputs:
      salida: ${{ steps.step_1.outputs.Mi_variable }}
    # pasos
    steps:
      - name: Print mensaje
        run: echo "${{ matrix.message }}" 